---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ll.
--- DateTime: 11/11/2021 17:14
---
fx_version 'adamant'

game 'gta5'

ui_page 'interface/html/index.html'
files {
    'interface/html/index.html',
	'interface/html/style.css',
    'interface/html/index.js',

}

shared_script {
    "config.lua"
}

client_script {
    "client/player/cl_connection.lua",
    "client/fonction.lua",
    "client/command/command.lua",
    "client/main.lua",
    "client/player/inventory.lua",
    "client/player/money.lua",
    "interface/intHud.lua",
    "client/player/jobs.lua"
}

server_script {
    "items.lua",
    "server/player/sv_connection.lua",
    "server/fonction.lua",
    "server/command/command.lua",
    "server/player/inventory.lua",
    "server/player/money.lua",
    "server/player/jobs.lua"

}