---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ll.
--- DateTime: 13/11/2021 23:02
---

Item = {
    {name = "bread",label = "pain", weight = 1.0, usable = true },
    {name = "water",label = "eau",weight = 1.5 , usable = true}
}