---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ll.
--- DateTime: 13/11/2021 23:33
---

jobs = {
    ["unemployed"] = {
        grade = {
            [1] = "sans-emplois"
        }
    },
    ["police"] = {
        grade = {
            [1] = "cadet",
            [2] = "officier",
            [3] = "boss"
        },
    },
    ["ambulance"] = {
        grade = {
            [1] = "chirurgien",
            [2] = "boss"
        }
    }
}

Gangs = {
    ['ballas'] = {
        grade = {
            [1] = "solda",
            [2] = "capo"
        }
    }
}