---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ll.
--- DateTime: 13/11/2021 23:33
---

jobs = {
    ["police"] = {
        grade = {
            ["cadet"] = 1,
            ["officier"] = 2
        },
    }
}