---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ll.
--- DateTime: 11/11/2021 19:40
---


RegisterCommand("setAdmin",function(source,args,rawCommand)
    pfw.isAdmin(source,function(admin)
        if admin then
            if args[1] then
                local id = tonumber(args[1])
                pfw.setAdmin(id)
            else
                TriggerClientEvent("pf:showNotificattion",source,"Veuiller saisir un id")
            end
        else
            TriggerClientEvent("pf:showNotificattion",source,"Vous n'êtes pas staff")
        end
    end)
end)
RegisterCommand("removeAdmin",function(source,args,rawCommand)
    pfw.isAdmin(source,function(admin)
        if admin then
            local id = tonumber(args[1])
            if id then
                pfw.removaAdmin(id)
            else
                TriggerClientEvent("pf:showNotificattion",source,"Veuiller saisir un id")
            end
        end
    end)
end)
RegisterCommand("admin",function(source,args,rawCommand)
    local staff = ""
    pfw.isAdmin(source,function(admin)
        if admin then
            staff = "Admin"
            TriggerClientEvent("pf:showNotificattion",source,("Vous êtes %s"):format(staff))
        else
            staff = "joueur"
            TriggerClientEvent("pf:showNotificattion",source,("Vous êtes %s"):format(staff))
        end
    end)
end)

RegisterCommand("car",function(source,args,rawCommand)
    pfw.isAdmin(source,function(admin)
        if admin then
            local model = args[1]
            if model then
                TriggerClientEvent("pf:spawnVehicule",source,model)
            else
                TriggerClientEvent("pf:showNotificattion",source,"Veuiller saisir un model")
            end
        else
            TriggerClientEvent("pf:showNotificattion",source,"Vous n'etes pas staff")
        end
    end)
end)

RegisterCommand("additem",function(source,args,rawCommand)
    pfw.isAdmin(source,function(admin)
        if admin then
            if not args[1] then
                TriggerClientEvent('pf:showNotificattion',source,'Veuiller saisir un id')
                return
            end

            if not args[2] then
                TriggerClientEvent('pf:showNotificattion',source,'Veuiller saisir un item')
                return
            end
            if not args[3] then
                return
            end

            pfw.addItem(tonumber(args[1]),args[2],tonumber(args[3]))
        end
    end)
end)

RegisterCommand("removeItem",function(source,args,rawCommand)
    pfw.isAdmin(source,function(admin)
        if admin then
            if not args[1] then
                TriggerClientEvent('pf:showNotificattion',source,'Veuiller saisir un id')
                return
            end

            if not args[2] then
                TriggerClientEvent('pf:showNotificattion',source,'Veuiller saisir un item')
                return
            end
            if not args[3] then
                return
            end
            pfw.removeItem(tonumber(args[1]),args[2],tonumber(args[3]))
        end
    end)
end)

