---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ll.
--- DateTime: 11/11/2021 17:14
---

AddEventHandler('playerSpawned',function()
    TriggerServerEvent('pf:SpawnPlayer')
end)

RegisterNetEvent("pf:lastPosition")
AddEventHandler("pf:lastPosition",function(PosX,PosY,PosZ)
    Citizen.Wait(1)
    local defaultModel = GetHashKey('mp_m_freemode_01')
    RequestModel(defaultModel)
    while not HasModelLoaded(defaultModel)do
        Wait(1)
    end
    SetPlayerModel(PlayerId(),defaultModel)
    SetPedDefaultComponentVariation(PlayerPedId())
    SetModelAsNoLongerNeeded(defaultModel)
    SetEntityCoords(PlayerPedId(),PosX,PosY,PosZ,1,0,0,1)
end)

CreateThread(function()
    while true do
        Wait(5000)
        lastX, lastY , lastZ = table.unpack(GetEntityCoords(PlayerPedId(),true))
        TriggerServerEvent('pf_SavePlayerPosition',lastX, lastY , lastZ)
    end
end)