---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ll.
--- DateTime: 13/11/2021 23:33
---


AddEventHandler('onResourceStart', function(resourceName)
    if (GetCurrentResourceName() ~= resourceName) then
        return
    end
    TriggerServerEvent("setDefaultJob")
    TriggerServerEvent("GetJobUser")
    TriggerServerEvent("GetGangUser")
end)



