---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ll.
--- DateTime: 13/11/2021 16:24
---

AddEventHandler("playerSpawned",function()


end)

AddEventHandler('onClientResourceStart', function (resourceName)
    if(GetCurrentResourceName() ~= resourceName) then
        return
    end
    TriggerServerEvent("pf:getMoneyInfo")
    TriggerServerEvent('pf:setinfousers')
end)

