---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ll.
--- DateTime: 13/11/2021 16:24
---

AddEventHandler("playerSpawned",function()
    TriggerServerEvent('pf:setinfousers')

end)

AddEventHandler('onClientResourceStart', function (resourceName)
    if(GetCurrentResourceName() ~= resourceName) then
        return
    end
    TriggerServerEvent("pf:getMoneyInfo")

end)

