---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ll.
--- DateTime: 13/11/2021 19:51
---

RegisterNetEvent("pf:SendInfoMoney")
AddEventHandler("pf:SendInfoMoney",function(money)

    SendNuiMessage(json.encode({
        type = "setMoney",
        value = money
    }))
end)

RegisterNetEvent("pf:SendInfoMoneyçbank")
AddEventHandler("pf:SendInfoMoneyçbank",function(money)
    SendNuiMessage(json.encode({
        type = "setBank",
        value = money
    }))
end)