---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ll.
--- DateTime: 13/11/2021 19:51
---

RegisterNetEvent("pf:SendInfoMoney")
AddEventHandler("pf:SendInfoMoney",function(money)

    SendNuiMessage(json.encode({
        type = "setMoney",
        value = money
    }))
end)

RegisterNetEvent("pf:SendInfoMoneyçbank")
AddEventHandler("pf:SendInfoMoneyçbank",function(money)
    SendNuiMessage(json.encode({
        type = "setBank",
        value = money
    }))
end)

RegisterNetEvent("pf:senduserjob")
AddEventHandler("pf:senduserjob",function(job,grade)
    SendNuiMessage(json.encode({
        type = "setJob",
        value = job,
        grd = grade
    }))
end)

RegisterNetEvent("pf:senduserGang")
AddEventHandler("pf:senduserGang",function(gang,grade)
    SendNuiMessage(json.encode({
        type = "setGang",
        value = gang,
        grd = grade
    }))

end)