---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ll.
--- DateTime: 13/11/2021 23:36
---

RegisterNetEvent("setDefaultJob")
AddEventHandler("setDefaultJob",function()
    local source = source
    exports.mongodb:findOne({collection="users_infos",query = {identifier = GetPlayerIdentifier(source)}},function(succes,result)
        if not succes then
            print("^2[ERROR] Recherche de l'inventaire non succes")
            return
        end
        if not result[1] then
            return
        end
        if result[1].job then
            return
        end
        exports.mongodb:updateOne({ collection="users_infos", query = { _id = result[1]._id }, update = { ["$set"] = { job = "unemployed", grade = 0 } } })
        print("^2[MongoDb] Job crée avec succes")
    end)
end)


setJob = function(id,jobs,grade)
    if not id then
        print("Id invalid")
        return
    end
    if not jobs then
        print("jobs invalid")
        return
    end
    if not grade then
        print("grade invalid")
        return
    end

end
