---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ll.
--- DateTime: 13/11/2021 16:25
---


pfw.getMoney = function(id,cb)
    exports.mongodb:findOne({ collection="users_infos", query = { identifier = GetPlayerIdentifier(id) } }, function (success, result)
        if not success then
            print("[MongoDB][Example] Error de recherche infos users: "..tostring(result))
            return
        end
        if not result[1] then
            print("[utilisateur] introuvable")
            return
        end
        cb(result[1].money)
    end)
end

pfw.getMoneyBank = function(id,cb)
    exports.mongodb:findOne({ collection="users_infos", query = { identifier = GetPlayerIdentifier(id) } }, function (success, result)
        if not success then
            print("[MongoDB][Example] Error de recherche infos users: "..tostring(result))
            return
        end
        if not result[1] then
            print("[utilisateur] introuvable")
            return
        end
        cb(result[1].moneyBank)
    end)
end

pfw.addMoney = function(id,montant)
    exports.mongodb:findOne({ collection="users_infos", query = { identifier = GetPlayerIdentifier(id) } }, function (success, result)
        if not success then
            print("[MongoDB][Example] Error de recherche infos users: "..tostring(result))
            return
        end
        if not result[1] then
            print("[utilisateur] introuvable")
            return
        end
        local newMontant = result[1].money + montant
        exports.mongodb:updateOne({ collection="users_infos", query = { _id = result[1]._id }, update = { ["$set"] = { money = newMontant } } })
        TriggerClientEvent("pf:SendInfoMoney",id,newMontant)
        TriggerClientEvent("pf:showNotificattion",id,("Vous avez recu %s ~g~$"):format(montant))

    end)
end

pfw.addMoneyBank = function(id,montant)
    exports.mongodb:findOne({ collection="users_infos", query = { identifier = GetPlayerIdentifier(id) } }, function (success, result)
        if not success then
            print("[MongoDB][Example] Error de recherche infos users: "..tostring(result))
            return
        end
        if not result[1] then
            print("[utilisateur] introuvable")
            return
        end
        local newMontant = result[1].moneyBank + montant
        exports.mongodb:updateOne({ collection="users_infos", query = { _id = result[1]._id }, update = { ["$set"] = { moneyBank = newMontant } } })
        TriggerClientEvent("pf:SendInfoMoneyçbank",id,result[1].moneyBank)
        TriggerClientEvent("pf:showNotificattion",id,("Vous avez recu %s ~g~$ ~s~ en banque"):format(montant))

    end)
end

pfw.removeMoney = function(id,montant)
    exports.mongodb:findOne({ collection="users_infos", query = { identifier = GetPlayerIdentifier(id) } }, function (success, result)
        if not success then
            print("[MongoDB][Example] Error de recherche infos users: "..tostring(result))
            return
        end
        if not result[1] then
            print("[utilisateur] introuvable")
            return
        end
        if tonumber(result[1].money) >= tonumber(montant) then
            local newMontant = result[1].money - montant
            exports.mongodb:updateOne({ collection="users_infos", query = { _id = result[1]._id }, update = { ["$set"] = { money = newMontant } } })
            TriggerClientEvent("pf:SendInfoMoney",id,newMontant)
        else
            TriggerClientEvent('pf:showNotificattion',id,"Montant invalid")
        end
    end)
end

pfw.removeMoneyBank = function(id,montant)
    exports.mongodb:findOne({ collection="users_infos", query = { identifier = GetPlayerIdentifier(id) } }, function (success, result)
        if not success then
            print("[MongoDB][Example] Error de recherche infos users: "..tostring(result))
            return
        end
        if not result[1] then
            print("[utilisateur] introuvable")
            return
        end
        if result[1].moneyBank >= montant then
            local newMontant = result[1].moneyBank - montant
            exports.mongodb:updateOne({ collection="users_infos", query = { _id = result[1]._id }, update = { ["$set"] = { moneyBank = newMontant } } })
            TriggerClientEvent("pf:SendInfoMoneyçbank",id,result[1].moneyBank)
        else
            TriggerClientEvent('pf:showNotificattion',id,"Montant invalid")
        end
    end)
end