---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ll.
--- DateTime: 11/11/2021 17:14
---


AddEventHandler('playerConnecting', function(name, setKickReason, deferrals)
    local source = source
    local identifiers = GetPlayerIdentifiers(source)
    local identifier

    for k, v in ipairs(identifiers) do
        if string.match(v, 'steam:') then
            identifier = v
            break
        end
    end

    if not identifier then
        deferrals.done('You need open steam')
    else
        deferrals.done()
        exports.mongodb:findOne({ collection="users", query = { identifier = identifier } }, function (success, result)
            if not success then
                print("[MongoDB][Example] Error in findOne: "..tostring(result))
                return
            end
            -- Print user if already exists
            if #result > 0 then
                print("^2[MongoDB][Example] User is already created")
                return
            end
            if not result[1] then
                print("^2[MongoDB][Example] User does not exist. Creating...")
                exports.mongodb:insertOne({ collection="users", document = { identifier = identifier , position = '{-269.4, -955.3,31.2}' ,isAdmin = false} }, function (success, result, insertedIds)
                    if not success then
                        print("[MongoDB][Example] Error in insertOne: "..tostring(result))
                        return
                    end
                    print("[MongoDB][Example] User created. New ID: "..tostring(insertedIds[1]))
                end)
             end
        end)
    end
end)

RegisterNetEvent("pf:SpawnPlayer")
AddEventHandler("pf:SpawnPlayer",function()
    local source = source
    exports.mongodb:findOne({collection="users", query = {identifier = GetPlayerIdentifier(source)}},function(success, result)
        if not success then
            print("[MongoDB][Example] Error in findOne: "..tostring(result))
            return
        end
        if result[1] then
            local SpawnPos = json.decode(result[1].position)
            TriggerClientEvent("pf:lastPosition",source,SpawnPos[1],SpawnPos[2],SpawnPos[3])
        end
    end)
end)

RegisterNetEvent("pf_SavePlayerPosition")
AddEventHandler("pf_SavePlayerPosition",function(posX,posY,posZ)
    local source = source
    exports.mongodb:updateOne({ collection="users", query = { identifier = GetPlayerIdentifier(source) }, update = { ["$set"] = { position = ("{%s,%s,%s}"):format(posX,posY,posZ) } } })
end)

